### ISSUE TITLE
数据集中的深度信息

### ISSUE THREAD

**Issue by HalvesChen** [jiwei0921/RGBD-SOD-datasets#7]
数据中的深度是真实深度么？归一化的化需要如何处理？

**Comment by DVSOD** [comment]
是的，均为真实深度。你可以直接参考一些RGB-D的算法进行直接归一化处理，例如 BBSnet. https://github.com/zyjwuyan/BBS-Net

**Comment by jiwei0921** [comment]
是的，均为真实深度。你可以直接参考一些RGB-D的算法进行直接归一化处理，例如 BBSnet. https://github.com/zyjwuyan/BBS-Net
